version: 2.1
jobs:
  publish:
    docker:
      - image: squidfunk/mkdocs-material
    steps:
      - add_ssh_keys:
          fingerprints:
            - "21:cd:f9:49:0e:d6:8d:cf:b9:51:ca:7b:04:bb:88:c1"
      - checkout
      - run:
          name: Build
          command: |
            mv .git /tmp/
            cd mkdocs
            mkdocs build
            cp -r site/* /tmp/
      - run:
          name: Publish
          command: |
            cd /tmp/
            apk add --no-cache git openssh-client
            git config user.email "circleci@circle.com"
            git config user.name "circleci"
            git checkout --orphan gh-pages
            git add . && git commit -m "[ci skip] Publish"
            git push --force origin gh-pages

workflows:
  version: 2
  publish:
    jobs:
    - publish:
        filters:
          branches:
            only: master
